config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :subreddits do
    resources :posts
  end
  resources :posts do
    member do
      put 'like', to: "posts#upvote"
      put 'dislike', to: "posts#downvote"
    end
  end

  get 'posts/:id/redirect' => 'posts#redirect', :as => :link_redirect

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  belongs_to :subreddit
  acts_as_votable
  has_many :comments, :as => :commentable 
  before_save :unique_url

  def unique_url
    post = Post.where(:url => self.url)
      if post
        post.upvote
        self.errors_add(:message, 'url has already been posted')
        false
      else
        true
      end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :set_subreddit_options, only: [:new, :edit, :update, :create]

  # GET /posts
  # GET /posts.json
  def index
    if params[:subreddit_id]
      @subreddit = Subreddit.where(:name => params[:subreddit_id]).first
      @posts = @subreddit.posts.order(:cached_votes_up => :desc)
    else
      @posts = Post.order(:cached_votes_up => :desc)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post= Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to :back
  end

  def redirect
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to @post.url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_subreddit_options
      @subreddit_options = Subreddit.all.collect{ |subreddit| [subreddit.name, subreddit.id] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :summary, :subreddit_id)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, :value => "https://"%>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id, options_for_select(@user_options, @post.user_id) %>
  </div>
  <div class="field">
    <%= f.label :subreddit_id %><br>
    <%= f.number_field :subreddit_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>What's Hot</h1>


<div class="container-fluid">
  <% @posts.each do |post| %>
    <div class="row clearfix container">
      <ul class="list-unstyled list-inline">
        <li>
          <div class="btn-group span4 text-center">
            <ul class="list-unstyled">
              <li>
                <%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
                  <span class="glyphicon glyphicon-chevron-up"></span>
                <% end %>
              </li>
              <li><%= post.get_upvotes.size - post.get_downvotes.size %></li>
              <li>
                <%= link_to dislike_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
                  <span class="glyphicon glyphicon-chevron-down">
                <% end %>
              </li>
              <br>
              <br>
              <br>
              <br>
              <br>
            </ul>
          </div>
        </li>
        <li>
          <div class="span8">
            <ul class="list-unstyled">
              <li><h3><%= link_to post.title, link_redirect_path(post) %></h3></li>
              <li><%= post.summary %></li>
              <li><h5>Submitted <%= time_ago_in_words(post.created_at) %> ago by <em><%= post.user.name %></em></h5></li>
              <li>
                <ul class="list-unstyled list-inline">
                  <li><h6><%= link_to 'Show', post %></h6></li>
                  <li>
                    <% if post.user == current_user %>
                      <h6><%= link_to 'Edit', edit_post_path(post) %> <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></h6>
                      <% end %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Votes:</strong>
  <%= @post.get_upvotes.size - @post.get_downvotes.size %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %></a>
</p>

<p>
  <strong>Summary:</strong>
  <%= @post.summary %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<p>
  <strong>Subreddit:</strong>
  <%= @post.subreddit_id %>
</p>


<% if @post.user == current_user %>
	<div class="btn-group">
		<%= link_to 'Back', :back, class: "btn btn-default" %>
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default" %>
		<%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
	</div>
<% end %>